{{- if eq .Values.redis.type "internal" -}}
{{- if and .Values.redis.internal.usePassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.redis" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: redis
type: Opaque
data:
  {{- if .Values.redis.internal.password }}
  redis-password: {{ .Values.redis.internal.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end -}}
{{- end -}}